networks:
  file_storage_net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server
      - client
    networks:
      - file_storage_net

  server:
    container_name: file-storage-server
    restart: always
    build: ./server
    volumes:
      - uploads:/app/uploads
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://root:admin@db:5432/file_storage_db?schema=public
      JWT_SECRET: YourString
      JWT_SECRET_REFRESH: YourAnotherString
      CLIENT_URL: http://disk.sadrozzy.me:3000
    depends_on:
      - db
    networks:
      - file_storage_net

  client:
    container_name: file-storage-client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://disk.sadrozzy.me:4000
      NEXT_PUBLIC_STATIC_URL: http://disk.sadrozzy.me:4000/uploads
    networks:
      - file_storage_net

  db:
    container_name: postgres
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: file_storage_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - file_storage_net

volumes:
  db-data:
  uploads: