networks:
  file-storage-net:

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server
      - client
    networks:
      - file-storage-net

  server:
    container_name: file-storage-server
    build: ./server
    volumes:
      - uploads:/app/uploads
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://username:password@db:5432/file_storage_db?schema=public
      JWT_SECRET: YourString
      JWT_SECRET_REFRESH: YourAnotherString
      CLIENT_URL: http://disk.sadrozzy.me:3000
    depends_on:
      - db
    networks:
      - file-storage-net

  client:
    container_name: file-storage-client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://disk.sadrozzy.me:4000
      NEXT_PUBLIC_STATIC_URL: http://disk.sadrozzy.me:4000/uploads
    networks:
      - file-storage-net

  db:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_storage_db
    networks:
      - file-storage-net

volumes:
  db-data:
  uploads: